#############################################################################
# Makefile for building: HW
# Generated by qmake (2.01a) (Qt 4.7.0) on: ?? ???? 22 18:23:55 2010
# Project:  HW.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile HW.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WEBKIT_LIB -DQT_SQL_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4/QtSql -I/usr/include/qt4/QtWebKit -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib ./lib/libqxmlrpc.a -lQtWebKit -lQtSql -lQtXml -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		aliasgui/newbook/newbook.cpp \
		aliasgui/inserttable/inserttable.cpp \
		aliasgui/imgprop.cpp \
		aliasgui/settings.cpp \
		aliasgui/href.cpp \
		aliasgui/syncmain.cpp \
		aliasgui/syntaxhilight.cpp \
		aliasgui/adifference.cpp \
		aliasgui/about.cpp moc_mainwindow.cpp \
		moc_newbook.cpp \
		moc_inserttable.cpp \
		moc_imgprop.cpp \
		moc_settings.cpp \
		moc_href.cpp \
		moc_syncmain.cpp \
		moc_syntaxhilight.cpp \
		moc_adifference.cpp \
		moc_about.cpp \
		qrc_main.cpp
OBJECTS       = main.o \
		mainwindow.o \
		newbook.o \
		inserttable.o \
		imgprop.o \
		settings.o \
		href.o \
		syncmain.o \
		syntaxhilight.o \
		adifference.o \
		about.o \
		moc_mainwindow.o \
		moc_newbook.o \
		moc_inserttable.o \
		moc_imgprop.o \
		moc_settings.o \
		moc_href.o \
		moc_syncmain.o \
		moc_syntaxhilight.o \
		moc_adifference.o \
		moc_about.o \
		qrc_main.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		HW.pro
QMAKE_TARGET  = HW
DESTDIR       = 
TARGET        = HW

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_newbook.h ui_inserttable.h ui_imgprop.h ui_settings.h ui_href.h ui_syncmain.h ui_syntaxhilight.h ui_adifference.h ui_about.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: HW.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtWebKit.prl \
		/usr/lib/libQtSql.prl \
		/usr/lib/libQtXml.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtNetwork.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile HW.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtWebKit.prl:
/usr/lib/libQtSql.prl:
/usr/lib/libQtXml.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtNetwork.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile HW.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/HW1.0.0 || $(MKDIR) .tmp/HW1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/HW1.0.0/ && $(COPY_FILE) --parents mainwindow.h aliasgui/newbook/newbook.h aliasgui/inserttable/inserttable.h aliasgui/imgprop.h aliasgui/settings.h aliasgui/href.h aliasgui/syncmain.h aliasgui/syntaxhilight.h aliasgui/adifference.h aliasgui/about.h .tmp/HW1.0.0/ && $(COPY_FILE) --parents res/main.qrc .tmp/HW1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp aliasgui/newbook/newbook.cpp aliasgui/inserttable/inserttable.cpp aliasgui/imgprop.cpp aliasgui/settings.cpp aliasgui/href.cpp aliasgui/syncmain.cpp aliasgui/syntaxhilight.cpp aliasgui/adifference.cpp aliasgui/about.cpp .tmp/HW1.0.0/ && $(COPY_FILE) --parents mainwindow.ui aliasgui/newbook/newbook.ui aliasgui/inserttable/inserttable.ui aliasgui/imgprop.ui aliasgui/settings.ui aliasgui/href.ui aliasgui/syncmain.ui aliasgui/syntaxhilight.ui aliasgui/adifference.ui aliasgui/about.ui .tmp/HW1.0.0/ && (cd `dirname .tmp/HW1.0.0` && $(TAR) HW1.0.0.tar HW1.0.0 && $(COMPRESS) HW1.0.0.tar) && $(MOVE) `dirname .tmp/HW1.0.0`/HW1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/HW1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_newbook.cpp moc_inserttable.cpp moc_imgprop.cpp moc_settings.cpp moc_href.cpp moc_syncmain.cpp moc_syntaxhilight.cpp moc_adifference.cpp moc_about.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_newbook.cpp moc_inserttable.cpp moc_imgprop.cpp moc_settings.cpp moc_href.cpp moc_syncmain.cpp moc_syntaxhilight.cpp moc_adifference.cpp moc_about.cpp
moc_mainwindow.cpp: aliasgui/href.h \
		aliasgui/syncmain.h \
		3thd/xmlrpc/client.h \
		3thd/xmlrpc/variant.h \
		mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_newbook.cpp: aliasgui/newbook/newbook.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) aliasgui/newbook/newbook.h -o moc_newbook.cpp

moc_inserttable.cpp: aliasgui/inserttable/inserttable.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) aliasgui/inserttable/inserttable.h -o moc_inserttable.cpp

moc_imgprop.cpp: aliasgui/imgprop.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) aliasgui/imgprop.h -o moc_imgprop.cpp

moc_settings.cpp: aliasgui/settings.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) aliasgui/settings.h -o moc_settings.cpp

moc_href.cpp: aliasgui/href.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) aliasgui/href.h -o moc_href.cpp

moc_syncmain.cpp: 3thd/xmlrpc/client.h \
		3thd/xmlrpc/variant.h \
		aliasgui/syncmain.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) aliasgui/syncmain.h -o moc_syncmain.cpp

moc_syntaxhilight.cpp: aliasgui/syntaxhilight.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) aliasgui/syntaxhilight.h -o moc_syntaxhilight.cpp

moc_adifference.cpp: aliasgui/adifference.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) aliasgui/adifference.h -o moc_adifference.cpp

moc_about.cpp: aliasgui/about.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) aliasgui/about.h -o moc_about.cpp

compiler_rcc_make_all: qrc_main.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_main.cpp
qrc_main.cpp: res/main.qrc \
		res/LICENSE.LGPL \
		res/welcome/index.html \
		res/welcome/images/button-bg.jpg \
		res/welcome/images/footer.jpg \
		res/welcome/images/square-green.png \
		res/welcome/images/header.jpg \
		res/welcome/images/bullet.gif \
		res/welcome/images/content.jpg \
		res/welcome/images/Envision.css \
		res/welcome/images/dots.jpg \
		res/welcome/images/menu.jpg \
		res/default/index.html \
		res/default/default.png \
		res/default/images/button-bg.jpg \
		res/default/images/footer.jpg \
		res/default/images/square-green.png \
		res/default/images/header.jpg \
		res/default/images/bullet.gif \
		res/default/images/content.jpg \
		res/default/images/Envision.css \
		res/default/images/dots.jpg \
		res/default/images/menu.jpg \
		res/icons/emblem-unreadable.png \
		res/icons/accessories-text-editor.png \
		res/icons/Downloads.png \
		res/icons/document.png \
		res/icons/emblem-readonly.png \
		res/icons/emblem-web.png \
		res/icons/x-office-document.png \
		res/icons/preferences-desktop.png \
		res/icons/file-manager.png \
		res/icons/tools-report-bug.png \
		res/icons/Sites.png \
		res/icons/Sygate.png \
		res/textimg/textjustify.png \
		res/textimg/lc_underlinedouble.png \
		res/textimg/textbold.png \
		res/textimg/lc_mergecells.png \
		res/textimg/fileprint.png \
		res/textimg/zoomout.png \
		res/textimg/dataeditor_icon04.png \
		res/textimg/filenew.png \
		res/textimg/list-remove.png \
		res/textimg/lc_underline.png \
		res/textimg/process-stop.png \
		res/textimg/textcenter.png \
		res/textimg/lx03158.png \
		res/textimg/lc_adddatefield.png \
		res/textimg/editundo.png \
		res/textimg/textright.png \
		res/textimg/lc_italic.png \
		res/textimg/sx10603.png \
		res/textimg/textleft.png \
		res/textimg/image-settings.png \
		res/textimg/zoomin.png \
		res/textimg/format-indent-less.png \
		res/textimg/dataeditor_icon02.png \
		res/textimg/lc_bold.png \
		res/textimg/list-add.png \
		res/textimg/fileopen.png \
		res/textimg/dataeditor_icon03.png \
		res/textimg/filesave.png \
		res/textimg/editpaste.png \
		res/textimg/format-justify-fill.png \
		res/textimg/editcopy.png \
		res/textimg/textitalic.png \
		res/textimg/editredo.png \
		res/textimg/dataeditor_icon01.png \
		res/textimg/textunder.png \
		res/textimg/editcut.png \
		res/textimg/exportpdf.png \
		res/textimg/format-indent-more.png \
		res/textimg/lc_addtable.png \
		res/syntaxhighlighter/scripts/shBrushMathematica.js \
		res/syntaxhighlighter/scripts/shBrushColdFusion.js \
		res/syntaxhighlighter/scripts/shBrushDelphi.js \
		res/syntaxhighlighter/scripts/shBrushMatlabSimple.js \
		res/syntaxhighlighter/scripts/shBrushSql.js \
		res/syntaxhighlighter/scripts/shBrushAda.js \
		res/syntaxhighlighter/scripts/shLegacy.js \
		res/syntaxhighlighter/scripts/shCore.js \
		res/syntaxhighlighter/scripts/shBrushCSharp.js \
		res/syntaxhighlighter/scripts/shBrushLua.js \
		res/syntaxhighlighter/scripts/shBrushPerl.js \
		res/syntaxhighlighter/scripts/shBrushScala.js \
		res/syntaxhighlighter/scripts/shBrushPlain.js \
		res/syntaxhighlighter/scripts/shBrushFSharp.js \
		res/syntaxhighlighter/scripts/shBrushNasm8086.js \
		res/syntaxhighlighter/scripts/shBrushPhp.js \
		res/syntaxhighlighter/scripts/shBrushVb.js \
		res/syntaxhighlighter/scripts/shBrushClojure.js \
		res/syntaxhighlighter/scripts/shBrushLatex.js \
		res/syntaxhighlighter/scripts/shBrushPowerShell.js \
		res/syntaxhighlighter/scripts/shBrushBat.js \
		res/syntaxhighlighter/scripts/shBrushJavaFX.js \
		res/syntaxhighlighter/scripts/shBrushRpgle.js \
		res/syntaxhighlighter/scripts/shBrushErlang.js \
		res/syntaxhighlighter/scripts/shBrushBash.js \
		res/syntaxhighlighter/scripts/shBrushGroovy.js \
		res/syntaxhighlighter/scripts/shBrushAhk.js \
		res/syntaxhighlighter/scripts/shBrushYaml.js \
		res/syntaxhighlighter/scripts/shBrushRouterOS.js \
		res/syntaxhighlighter/scripts/clipboard.swf \
		res/syntaxhighlighter/scripts/shBrushProcessing.js \
		res/syntaxhighlighter/scripts/shBrushCss.js \
		res/syntaxhighlighter/scripts/shBrushXml.js \
		res/syntaxhighlighter/scripts/shBrushJScript.js \
		res/syntaxhighlighter/scripts/shBrushCpp.js \
		res/syntaxhighlighter/scripts/shBrushJava.js \
		res/syntaxhighlighter/scripts/shBrushPython.js \
		res/syntaxhighlighter/scripts/shBrushLsl.js \
		res/syntaxhighlighter/scripts/shBrushAS3.js \
		res/syntaxhighlighter/scripts/shBrushSahi.js \
		res/syntaxhighlighter/scripts/shBrushMatlab.js \
		res/syntaxhighlighter/scripts/shBrushAppleScript.js \
		res/syntaxhighlighter/scripts/shBrushAsm.js \
		res/syntaxhighlighter/scripts/shBrushDiff.js \
		res/syntaxhighlighter/scripts/shBrushRuby.js \
		res/syntaxhighlighter/scripts/shBrushObjectiveC.js \
		res/syntaxhighlighter/styles/shThemeMidnight.css \
		res/syntaxhighlighter/styles/shThemeEclipse.css \
		res/syntaxhighlighter/styles/magnifier.png \
		res/syntaxhighlighter/styles/shThemeFadeToGrey.css \
		res/syntaxhighlighter/styles/shThemeRDark.css \
		res/syntaxhighlighter/styles/printer.png \
		res/syntaxhighlighter/styles/shCore.css \
		res/syntaxhighlighter/styles/page_white_copy.png \
		res/syntaxhighlighter/styles/shThemeDjango.css \
		res/syntaxhighlighter/styles/page_white_code.png \
		res/syntaxhighlighter/styles/shThemeDefault.css \
		res/syntaxhighlighter/styles/shThemeEmacs.css \
		res/syntaxhighlighter/styles/help.png
	/usr/bin/rcc -name main res/main.qrc -o qrc_main.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_newbook.h ui_inserttable.h ui_imgprop.h ui_settings.h ui_href.h ui_syncmain.h ui_syntaxhilight.h ui_adifference.h ui_about.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_newbook.h ui_inserttable.h ui_imgprop.h ui_settings.h ui_href.h ui_syncmain.h ui_syntaxhilight.h ui_adifference.h ui_about.h
ui_mainwindow.h: mainwindow.ui
	/usr/bin/uic-qt4 mainwindow.ui -o ui_mainwindow.h

ui_newbook.h: aliasgui/newbook/newbook.ui
	/usr/bin/uic-qt4 aliasgui/newbook/newbook.ui -o ui_newbook.h

ui_inserttable.h: aliasgui/inserttable/inserttable.ui
	/usr/bin/uic-qt4 aliasgui/inserttable/inserttable.ui -o ui_inserttable.h

ui_imgprop.h: aliasgui/imgprop.ui
	/usr/bin/uic-qt4 aliasgui/imgprop.ui -o ui_imgprop.h

ui_settings.h: aliasgui/settings.ui
	/usr/bin/uic-qt4 aliasgui/settings.ui -o ui_settings.h

ui_href.h: aliasgui/href.ui
	/usr/bin/uic-qt4 aliasgui/href.ui -o ui_href.h

ui_syncmain.h: aliasgui/syncmain.ui
	/usr/bin/uic-qt4 aliasgui/syncmain.ui -o ui_syncmain.h

ui_syntaxhilight.h: aliasgui/syntaxhilight.ui
	/usr/bin/uic-qt4 aliasgui/syntaxhilight.ui -o ui_syntaxhilight.h

ui_adifference.h: aliasgui/adifference.ui
	/usr/bin/uic-qt4 aliasgui/adifference.ui -o ui_adifference.h

ui_about.h: aliasgui/about.ui
	/usr/bin/uic-qt4 aliasgui/about.ui -o ui_about.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		aliasgui/href.h \
		aliasgui/syncmain.h \
		3thd/xmlrpc/client.h \
		3thd/xmlrpc/variant.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		aliasgui/href.h \
		aliasgui/syncmain.h \
		3thd/xmlrpc/client.h \
		3thd/xmlrpc/variant.h \
		ui_mainwindow.h \
		aliasgui/about.h \
		aliasgui/newbook/newbook.h \
		aliasgui/inserttable/inserttable.h \
		aliasgui/imgprop.h \
		aliasgui/syntaxhilight.h \
		aliasgui/settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

newbook.o: aliasgui/newbook/newbook.cpp aliasgui/newbook/newbook.h \
		ui_newbook.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o newbook.o aliasgui/newbook/newbook.cpp

inserttable.o: aliasgui/inserttable/inserttable.cpp aliasgui/inserttable/inserttable.h \
		ui_inserttable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o inserttable.o aliasgui/inserttable/inserttable.cpp

imgprop.o: aliasgui/imgprop.cpp aliasgui/imgprop.h \
		ui_imgprop.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o imgprop.o aliasgui/imgprop.cpp

settings.o: aliasgui/settings.cpp aliasgui/settings.h \
		ui_settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o settings.o aliasgui/settings.cpp

href.o: aliasgui/href.cpp aliasgui/href.h \
		ui_href.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o href.o aliasgui/href.cpp

syncmain.o: aliasgui/syncmain.cpp aliasgui/syncmain.h \
		3thd/xmlrpc/client.h \
		3thd/xmlrpc/variant.h \
		ui_syncmain.h \
		aliasgui/adifference.h \
		aliasgui/newbook/newbook.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o syncmain.o aliasgui/syncmain.cpp

syntaxhilight.o: aliasgui/syntaxhilight.cpp aliasgui/syntaxhilight.h \
		ui_syntaxhilight.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o syntaxhilight.o aliasgui/syntaxhilight.cpp

adifference.o: aliasgui/adifference.cpp aliasgui/adifference.h \
		ui_adifference.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o adifference.o aliasgui/adifference.cpp

about.o: aliasgui/about.cpp aliasgui/about.h \
		ui_about.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o about.o aliasgui/about.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_newbook.o: moc_newbook.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_newbook.o moc_newbook.cpp

moc_inserttable.o: moc_inserttable.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_inserttable.o moc_inserttable.cpp

moc_imgprop.o: moc_imgprop.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_imgprop.o moc_imgprop.cpp

moc_settings.o: moc_settings.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_settings.o moc_settings.cpp

moc_href.o: moc_href.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_href.o moc_href.cpp

moc_syncmain.o: moc_syncmain.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_syncmain.o moc_syncmain.cpp

moc_syntaxhilight.o: moc_syntaxhilight.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_syntaxhilight.o moc_syntaxhilight.cpp

moc_adifference.o: moc_adifference.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_adifference.o moc_adifference.cpp

moc_about.o: moc_about.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_about.o moc_about.cpp

qrc_main.o: qrc_main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_main.o qrc_main.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

